/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uinterface;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import persistence.*;

/**
 *
 * @author Marlon
 */
public class JFrame_Geral extends javax.swing.JFrame {

    private static final String FILENAME = "C:\\temp\\logClients.txt";
    private static List<Cliente> checked_in_list = new ArrayList<>();
    public static Scanner terminal = new Scanner(System.in);
    
    static Bar bar = new Bar();
    
    /**
     * Creates new form JFrame_Geral
     */
    public JFrame_Geral() {
        initComponents();
        jl_logFilePath.setText("Ao sair o log será criado no diretório: " + FILENAME);
    }
    
    public static void write_in_log() {
        BufferedWriter writer = null;
        String logPath="Log saved in ";
        
        try {
            
            File logFile = new File(FILENAME);
            
            logPath += logFile.getCanonicalPath();
            
            writer = new BufferedWriter(new FileWriter(logFile, true));                  
            for(int x=0; x < checked_in_list.size(); x++){
                writer.write(checked_in_list.get(x).toString());
                writer.newLine();
                writer.write("-----------------------------------");
                writer.newLine();
            }
            
        }catch (IOException e ) {
            e.printStackTrace();
        }finally {
            try {
                writer.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        
        System.out.println(logPath);
    } 
    
    public static void verify_client_passage(Cliente cli){
        for(int x=0; x < checked_in_list.size(); x++){
            if(cli.getCpf().equals(checked_in_list.get(x).getCpf())){
                return;
            }
        }
        checked_in_list.add(cli);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_botoes = new javax.swing.JPanel();
        jl_titulo = new javax.swing.JLabel();
        jb_checkin = new javax.swing.JButton();
        jb_listarClientes = new javax.swing.JButton();
        jb_qtdeClientes = new javax.swing.JButton();
        jb_distribuicaoGenero = new javax.swing.JButton();
        jb_distribuicaoSocios = new javax.swing.JButton();
        jb_checkout = new javax.swing.JButton();
        jb_pesquisaCPF = new javax.swing.JButton();
        jb_sair = new javax.swing.JButton();
        jl_logFilePath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_botoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jl_titulo.setText("Sistema para Rede de Bares");

        jb_checkin.setText("Check-In");
        jb_checkin.setPreferredSize(new java.awt.Dimension(105, 23));
        jb_checkin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_checkinMouseClicked(evt);
            }
        });

        jb_listarClientes.setText("Listar Clientes");
        jb_listarClientes.setPreferredSize(new java.awt.Dimension(105, 23));
        jb_listarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listarClientesMouseClicked(evt);
            }
        });

        jb_qtdeClientes.setText("Qtde Clientes");
        jb_qtdeClientes.setPreferredSize(new java.awt.Dimension(105, 23));
        jb_qtdeClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_qtdeClientesMouseClicked(evt);
            }
        });

        jb_distribuicaoGenero.setText("Distrib. Gênero");
        jb_distribuicaoGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_distribuicaoGeneroMouseClicked(evt);
            }
        });

        jb_distribuicaoSocios.setText("Distrib. Sócios");
        jb_distribuicaoSocios.setPreferredSize(new java.awt.Dimension(105, 23));
        jb_distribuicaoSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_distribuicaoSociosMouseClicked(evt);
            }
        });

        jb_checkout.setText("Check-Out");
        jb_checkout.setPreferredSize(new java.awt.Dimension(105, 23));
        jb_checkout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_checkoutMouseClicked(evt);
            }
        });

        jb_pesquisaCPF.setText("Pesquisa CPF");
        jb_pesquisaCPF.setPreferredSize(new java.awt.Dimension(105, 23));
        jb_pesquisaCPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_pesquisaCPFMouseClicked(evt);
            }
        });

        jb_sair.setText("Sair");
        jb_sair.setPreferredSize(new java.awt.Dimension(105, 23));
        jb_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_sairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_botoesLayout = new javax.swing.GroupLayout(jp_botoes);
        jp_botoes.setLayout(jp_botoesLayout);
        jp_botoesLayout.setHorizontalGroup(
            jp_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_botoesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_logFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jp_botoesLayout.createSequentialGroup()
                .addGroup(jp_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_botoesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jp_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_botoesLayout.createSequentialGroup()
                                .addComponent(jb_checkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_listarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_qtdeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_pesquisaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_botoesLayout.createSequentialGroup()
                                .addComponent(jb_distribuicaoGenero)
                                .addGap(18, 18, 18)
                                .addComponent(jb_distribuicaoSocios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_checkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_botoesLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jl_titulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_botoesLayout.setVerticalGroup(
            jp_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_botoesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_checkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_listarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_qtdeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_pesquisaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_distribuicaoGenero)
                    .addComponent(jb_distribuicaoSocios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_checkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jl_logFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_botoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_botoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_checkinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_checkinMouseClicked
        JFrame frame_CheckinCliente = new JFrame_Checkin();
        frame_CheckinCliente.setVisible(true);
    }//GEN-LAST:event_jb_checkinMouseClicked

    private void jb_listarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listarClientesMouseClicked
        JOptionPane.showMessageDialog(this, "Lista de clientes no bar:\n\n" + bar.show_all());
    }//GEN-LAST:event_jb_listarClientesMouseClicked

    private void jb_qtdeClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_qtdeClientesMouseClicked
        JOptionPane.showMessageDialog(this, "Quantidade de cliente no bar = " + bar.count_clients());
    }//GEN-LAST:event_jb_qtdeClientesMouseClicked

    private void jb_pesquisaCPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_pesquisaCPFMouseClicked
        String cpfPesq = (String)JOptionPane.showInputDialog(this,
                                                     "Digite o CPF do cliente (sem pontos ou traços):",
                                                     "Pesquisa por CPF",
                                                     JOptionPane.PLAIN_MESSAGE,
                                                     null,
                                                     null,
                                                     null);
        JOptionPane.showMessageDialog(this, bar.search_with_CPF(cpfPesq));
    }//GEN-LAST:event_jb_pesquisaCPFMouseClicked

    private void jb_distribuicaoGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_distribuicaoGeneroMouseClicked
        JOptionPane.showMessageDialog(this, "Distribuição por gênero:\n\n" + bar.percent_gender());
    }//GEN-LAST:event_jb_distribuicaoGeneroMouseClicked

    private void jb_distribuicaoSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_distribuicaoSociosMouseClicked
        JOptionPane.showMessageDialog(this, "Distribuição por sócios\n\n" + bar.count_associateds());
    }//GEN-LAST:event_jb_distribuicaoSociosMouseClicked

    private void jb_checkoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_checkoutMouseClicked
        String cpfOut = (String)JOptionPane.showInputDialog(this,
                                                     "Digite o CPF do cliente (sem pontos ou traços):",
                                                     "Check-Out de Clientes",
                                                     JOptionPane.PLAIN_MESSAGE,
                                                     null,
                                                     null,
                                                     null);
        JOptionPane.showMessageDialog(this, bar.client_out(cpfOut));
    }//GEN-LAST:event_jb_checkoutMouseClicked

    private void jb_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_sairMouseClicked
        write_in_log();
        System.exit(0);
    }//GEN-LAST:event_jb_sairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Geral().setVisible(true);
            }
        });
        
        Cliente cliente_1 = new Cliente("PEDRINHO"  , "03455699985", 17, true , false );
        Cliente cliente_2 = new Cliente("JUANA"     , "09684699005", 29, false, true  );
        Cliente cliente_3 = new Cliente("JUAU"      , "15425789336", 45, true , true  );
        Cliente cliente_4 = new Cliente("JUSICLEYDE", "85769300289", 19, false, false );
        Cliente cliente_5 = new Cliente("JULINHO"   , "77930179582", 22, true , true  );
        Cliente cliente_6 = new Cliente("GEREMIAS"  , "79635817582", 60, true , true  );
        
        //CLIENTES ENTRAM NO BAR
        bar.client_in(cliente_1);
        verify_client_passage(cliente_1);
        bar.client_in(cliente_2);
        verify_client_passage(cliente_2);
        bar.client_in(cliente_3);
        verify_client_passage(cliente_3);
        bar.client_in(cliente_4);
        verify_client_passage(cliente_4);
        bar.client_in(cliente_5);
        verify_client_passage(cliente_5);
        bar.client_in(cliente_6);
        verify_client_passage(cliente_6);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_checkin;
    private javax.swing.JButton jb_checkout;
    private javax.swing.JButton jb_distribuicaoGenero;
    private javax.swing.JButton jb_distribuicaoSocios;
    private javax.swing.JButton jb_listarClientes;
    private javax.swing.JButton jb_pesquisaCPF;
    private javax.swing.JButton jb_qtdeClientes;
    private javax.swing.JButton jb_sair;
    private javax.swing.JLabel jl_logFilePath;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JPanel jp_botoes;
    // End of variables declaration//GEN-END:variables
}
