/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uinterface;

import java.awt.event.ActionEvent;
import javax.swing.*;
import persistence.*;

/**
 *
 * @author Marlon
 */
public class JFrame_Checkin extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Checkin
     */
    public JFrame_Checkin() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_checkin = new javax.swing.JPanel();
        jl_nome = new javax.swing.JLabel();
        jtf_nome = new javax.swing.JTextField();
        jl_cpf = new javax.swing.JLabel();
        jtf_cpf = new javax.swing.JTextField();
        jl_idade = new javax.swing.JLabel();
        jtf_idade = new javax.swing.JTextField();
        jl_genero = new javax.swing.JLabel();
        jrb_masculino = new javax.swing.JRadioButton();
        jrb_feminino = new javax.swing.JRadioButton();
        jl_socio = new javax.swing.JLabel();
        jrb_ehSocio = new javax.swing.JRadioButton();
        jrb_naoEhSocio = new javax.swing.JRadioButton();
        jb_cadastrar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_checkin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jl_nome.setText("Nome:");

        jl_cpf.setText("CPF:");

        jl_idade.setText("Idade:");

        jl_genero.setText("Gênero:");

        jrb_masculino.setText("Masculino");

        jrb_feminino.setText("Feminino");

        jl_socio.setText("É sócio?");

        jrb_ehSocio.setText("Sim");

        jrb_naoEhSocio.setText("Não");

        jb_cadastrar.setText("Cadastrar");
        jb_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cadastrarMouseClicked(evt);
            }
        });

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_checkinLayout = new javax.swing.GroupLayout(jp_checkin);
        jp_checkin.setLayout(jp_checkinLayout);
        jp_checkinLayout.setHorizontalGroup(
            jp_checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_checkinLayout.createSequentialGroup()
                .addGroup(jp_checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_checkinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jp_checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_checkinLayout.createSequentialGroup()
                                .addComponent(jl_nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_checkinLayout.createSequentialGroup()
                                .addComponent(jl_cpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_cpf))
                            .addGroup(jp_checkinLayout.createSequentialGroup()
                                .addComponent(jl_idade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_idade)))
                        .addGroup(jp_checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_checkinLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jl_genero))
                            .addGroup(jp_checkinLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jrb_masculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb_feminino))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_checkinLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl_socio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrb_ehSocio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb_naoEhSocio))))
                    .addGroup(jp_checkinLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jb_cadastrar)
                        .addGap(31, 31, 31)
                        .addComponent(jb_cancelar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jp_checkinLayout.setVerticalGroup(
            jp_checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_checkinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nome)
                    .addComponent(jtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_genero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_cpf)
                    .addComponent(jtf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrb_masculino)
                    .addComponent(jrb_feminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_idade)
                    .addComponent(jtf_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_socio)
                    .addComponent(jrb_ehSocio)
                    .addComponent(jrb_naoEhSocio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cadastrar)
                    .addComponent(jb_cancelar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_checkin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_checkin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cancelarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jb_cancelarMouseClicked

    private void jb_cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cadastrarMouseClicked
        String nome = jtf_nome.getText();
        String cpf  = jtf_cpf.getText();
        int idade = Integer.parseInt(jtf_idade.getText());
        boolean genero;
        if(jrb_masculino.isFocusOwner()){
            genero = true;
        }else{
            genero = false;
        }
        boolean socio;
        if(jrb_ehSocio.isFocusOwner()){
            socio = true;
        }else{
            socio = false;
        }
        
        Cliente cli = new Cliente(nome, cpf, idade, genero, socio);
        JFrame_Geral.bar.client_in(cli);
        JFrame_Geral.verify_client_passage(cli);
    }//GEN-LAST:event_jb_cadastrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_cadastrar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JLabel jl_cpf;
    private javax.swing.JLabel jl_genero;
    private javax.swing.JLabel jl_idade;
    private javax.swing.JLabel jl_nome;
    private javax.swing.JLabel jl_socio;
    private javax.swing.JPanel jp_checkin;
    private javax.swing.JRadioButton jrb_ehSocio;
    private javax.swing.JRadioButton jrb_feminino;
    private javax.swing.JRadioButton jrb_masculino;
    private javax.swing.JRadioButton jrb_naoEhSocio;
    private javax.swing.JTextField jtf_cpf;
    private javax.swing.JTextField jtf_idade;
    private javax.swing.JTextField jtf_nome;
    // End of variables declaration//GEN-END:variables
}
